version: '3.8'

networks:
  appnetwork:
    name: appnetwork
    external: true

services:
  pm2dapp:
    image: nodepm2
    container_name: sw-pm2dapp
    working_dir: /var/www/dapp
    # restart: always
    expose:
      - 3000
    ports:
      - '3000:3000' # reflect from expose port to real port
    volumes:
      - ./:/var/www/dapp
      - /home/hero/ssl:/home/hero/ssl
    command: sh -c "npm install && npm run build && pm2-runtime start pm2.json"
    networks:
      appnetwork:
        ipv4_address: 172.168.0.3
